package com.demo.security.spring.suites;

import org.junit.platform.suite.api.SelectPackages;
import org.junit.platform.suite.api.Suite;
import org.junit.platform.suite.api.SuiteDisplayName;

/**
 * This suite validates that the hibernate generated schema and the schema.sql
 * created schema are identical. This allows for better confidence that schema generated by hibernate
 * for use with h2 during reflects the schema used at runtime with postgres.
 */
@Suite
@SuiteDisplayName("Validate Postgresql SQL created schema vs. Hibernate generated schema")
@SelectPackages("com.demo.security.spring.postgres")
public class ValidatePostgresSchema {

}
